import MediaSection from "@/components/landing-page/mediaSection";
import MenuSection from "@/components/landing-page/menuSection";
import "bootstrap/dist/css/bootstrap.min.css";
import "remixicon/fonts/remixicon.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LandingLayout({ children }) {
  return (
    <div>
      <MediaSection />
      <MenuSection />
      {children}
    </div>
  );
}
