import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import NotFound from "@/app/book/not-found";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  const cookieStore = cookies();
  if (!cookieStore.has("userId") || !cookieStore.has("role")) {
    redirect("/login");
  }
  const role = JSON.parse(cookieStore.get("role").value);
  if (role === "driver" || role === "admin") {
    return children;
  } else {
    return <NotFound />;
  }
}
