import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrintLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
